@startuml
package "MediAgenda" <<Rectangle>> {

    class UsuarioAplicacion #7dc4f6ff {
        + Nombre: string
        + Apellido: string
        + NumeroTelefono: string
        + NombreUsuario: string (IdentityUser)
        + Email: string (IdentityUser)
        + Doctor: Doctor
        + Paciente: Paciente
    }

    class Doctor #7dc4f6ff {
        + Usuario: UsuarioAplicacion
        + Especialidad: string
        + SobreMi: string
    }

    class Paciente #7dc4f6ff {
        + Usuario: UsuarioAplicacion
        + Seguro: Seguro
        + Identificacion: string
        + FechaNacimiento: DateTime
        + TipoSangre: TipoSangre
        + Genero: Genero
    }

    class Seguro {
        + Nombre: string
    }

    class Consulta {
        + Paciente: Paciente
        + Razon: Razon
        + DiaDisponible: DiaDisponible
        + Estado: EstadoConsulta
        + Turno: int
    }

    class Razon {
        + Titulo: string
        + Descripcion: string
        + Disponible: bool
    }

    class DiaDisponible {
        + Clinica: Clinica
        + HoraInicio: TimeOnly
        + HoraFin: TimeOnly
        + Fecha: DateOnly
        + Limite: int
    }

    class Clinica {
        + Nombre: string
        + Direccion: string
        + NumeroTelefono: string
    }

    class NotaConsulta {
        + Consulta: Consulta
        + Titulo: string
        + Contenido: string
        + CreadoEn: DateTime
        + ActualizadoEn: DateTime
    }

    class NotaPaciente {
        + Paciente: Paciente
        + Titulo: string
        + Contenido: string
        + CreadoEn: DateTime
        + ActualizadoEn: DateTime
    }

    class Receta {
        + Consulta: Consulta
        + RecomendacionesGenerales: string
        + CreadoEn: DateTime
        + UltimaImpresion: DateTime
    }

    class Medicina {
        + Nombre: string
        + Descripcion: string
        + Formato: string
    }

    class Analisis {
        + Nombre: string
        + Descripcion: string
    }

    class Permiso {
        + Nombre: string
        + Descripcion: string
    }

    class RecetaMedicina #ee9f9fff {
        + Receta: Receta
        + Medicina: Medicina
        + Instrucciones: string
    }

    class RecetaAnalisis #ee9f9fff {
        + Receta: Receta
        + Analisis: Analisis
        + Recomendaciones: string
    }

    class RecetaPermiso #ee9f9fff {
        + Receta: Receta
        + Permiso: Permiso
    }

    class MedicamentosActuales #ee9f9fff {
        + Paciente: Paciente
        + Medicina: Medicina
        + InicioMedicacion: DateOnly
        + FinMedicacion: DateOnly
    }

    class DocumentoMedico {
        + Paciente: Paciente
        + NombreArchivo: string
        + UrlArchivo: string
        + TipoDocumento: string
    }

    enum TipoSangre {
        A_Positivo
        A_Negativo
        B_Positivo
        B_Negativo
        AB_Positivo
        AB_Negativo
        O_Positivo
        O_Negativo
    }

    enum EstadoConsulta {
        Pendiente
        Confirmada
        Cancelada
    }

    enum Genero {
        Masculino
        Femenino
    }
}

' Relaciones

' Usuario
UsuarioAplicacion "1" -- "0..1" Doctor
UsuarioAplicacion "1" -- "0..1" Paciente

' Paciente
Paciente "1" -- "1" NotaPaciente
Paciente "*" -- "1" Seguro
Paciente "1" -- "*" Consulta
Paciente "1" -- "*" DocumentoMedico
Paciente "1" -- "*" MedicamentosActuales
Paciente -- TipoSangre
Paciente -- Genero

' Consultas
Consulta "*" -- "1" Razon
Consulta "*" -- "1" DiaDisponible
Consulta "1" -- "1" NotaConsulta
Consulta "1" -- "*" Receta
Consulta -- EstadoConsulta

' Clínica
Clinica "1" -- "*" DiaDisponible

' Prescripciones
Receta "1" -- "*" RecetaMedicina
Receta "1" -- "*" RecetaAnalisis
Receta "1" -- "*" RecetaPermiso

' Medicinas y Análisis
Medicina "1" -- "*" RecetaMedicina
Medicina "1" -- "*" MedicamentosActuales
Analisis "1" -- "*" RecetaAnalisis
Permiso "1" -- "*" RecetaPermiso

@enduml